name: simple_connection_checker
description: A simple package to check when the device is connected (connectivity) to internet. Also provide a method to listen for connection status changes.
version: 0.3.0
homepage: https://github.com/ajomuch92/simple-connection-checker

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
